export const breadcrumbsLabel = [
  { breadcrumb: "clanky", label: "články" },
  { breadcrumb: "aktuality", label: "aktuality" },
  { breadcrumb: "horoskola-skaly", label: "horoškola - skály" },
  { breadcrumb: "horoskola-vicedelky", label: "horoškola - vícedélky" },
  { breadcrumb: "lavinova-prevence", label: "lavinová prevence" },
  { breadcrumb: "lezeni-v-ledu", label: "lezení v ledu" },
  { breadcrumb: "zimni-lezeni", label: "zimní lezení" },
  { breadcrumb: "horokruh", label: "horokruh - lezecký kroužek" },
  { breadcrumb: "clenstvi-v-oddile", label: "pro členy" },
  { breadcrumb: "oddilove-akce", label: "oddílové akce" },
  { breadcrumb: "knihovna", label: "knihovna" },
  { breadcrumb: "pujcovna-vybaveni", label: "půjčovna vybavení" },
  { breadcrumb: "vyhody-clenstvi", label: "výhody členství" },
  { breadcrumb: "podminky-clenstvi", label: "podmínky členství" },
  { breadcrumb: "o-nas", label: "o nás" },
  { breadcrumb: "historie-oddilu", label: "historie oddílu" },
  { breadcrumb: "vedeni-oddilu", label: "vedení oddílu" },
  { breadcrumb: "instruktori-horoskoly", label: "instruktoři horoškoly" },
  { breadcrumb: "treneri-lezeni", label: "trenéři lezení" },
  { breadcrumb: "kontakt", label: "kontakt" },
  { breadcrumb: "dashboard-clanky", label: "články" },
  { breadcrumb: "dashboard-novinky", label: "novinky" },
  { breadcrumb: "kalendar", label: "kalendář" },
  { breadcrumb: "pujcovna", label: "půjčovna" },
  { breadcrumb: "uzivatele", label: "uživatelé" },
  { breadcrumb: "uvodni-info", label: "Úvodní informace" },
];
